### ISSUE TITLE
Map rendering errors

### ISSUE THREAD

**Issue by slango0513** [Kermalis/PokemonGameEngine#74]
There are some problems with the shadow layer of the blockset "TestBlocksetO_C". I use AMD 5700XT graphics card.
<img width="1920" alt="屏幕截图 2022-01-27 092639" src="https://user-images.githubusercontent.com/39337503/151274958-cdd6cf7d-a9f1-49f7-a140-44fb678fa556.png">
<img width="1920" alt="屏幕截图 2022-01-27 092815" src="https://user-images.githubusercontent.com/39337503/151274996-268a9afa-4814-4ef6-9f60-546b834f9288.png">

**Comment by Kermalis** [comment]
Hi, that's very strange, and it actually doesn't seem to be a problem with the transparency/shadows. It looks to only be happening to tiles from blocksets that aren't the first in the used blockset list. The first blockset to be loaded will be the top-left block of that map.

Doesn't happen for me (NVIDIA GTX 1660 Super) so it seems to be some default OpenGL setting being different between the vendors.

I'm also not sure what is causing those weird shapes since some of them aren't even complete triangles (like the corner of the house's roof). Can you change the top-left block of TestMapC to be from a different blockset? Make sure you build the assets after saving the map layout. I'd like to see what result shows then. It'd also be helpful if you found this happening in other places, but it seems to be from the second & third loaded blockset in this case

**Comment by slango0513** [comment]
<img width="584" alt="屏幕截图 2022-01-29 211818" src="https://user-images.githubusercontent.com/39337503/151662581-88048749-8b97-49cb-9d3b-3f2182bb0f17.png">
<img width="1920" alt="屏幕截图 2022-01-29 211711" src="https://user-images.githubusercontent.com/39337503/151662590-56fb1425-1353-4426-948b-0f73a2f2c759.png">
<img width="1920" alt="屏幕截图 2022-01-29 211741" src="https://user-images.githubusercontent.com/39337503/151662591-24113bf5-e38a-4902-a70e-2a856e683122.png">
<img width="550" alt="屏幕截图 2022-01-29 211953" src="https://user-images.githubusercontent.com/39337503/151662595-0ad3aa5d-971f-4b3a-b26f-31a2fbd2a55f.png">
<img width="1920" alt="屏幕截图 2022-01-29 211940" src="https://user-images.githubusercontent.com/39337503/151662597-f6a0e00c-5212-46d2-9cfd-5642107bba6f.png">
For some reason, TestMapC looks dark today, even though I recloned the repo. As shown I changed 3 places (circled with red lines), and the error still exists.

**Comment by slango0513** [comment]
Yes, this is really hard to fix. If you create a new branch with basic elements of blocksets listed in it, I'd be happy to provide screenshot feedback.

**Comment by Kermalis** [comment]
Alright, since it's the same error each time, and only on those tiles, I checked to see if the tileset images were funky and I found that the transparent pixels are really inconsistent

![image](https://user-images.githubusercontent.com/29823718/151663111-fdb0a0de-ecc0-4c0c-b173-177a3c0856af.png)
![image](https://user-images.githubusercontent.com/29823718/151663117-e4ba48dc-139d-4a32-8596-fafefa38831b.png)
![image](https://user-images.githubusercontent.com/29823718/151663127-542f5525-30e1-49c3-9398-d3e9daba2721.png)

Honestly I'm not sure how it got like that but I'll fix it up and commit it. Let me know if the latest commit fixed it

Also, the map is dark since it's adapting to your system time. You can disable that in the .csproj with `DEBUG_DISABLE_DAYTINT` in the debug constants

**Comment by slango0513** [comment]
<img width="1085" alt="屏幕截图 2022-01-29 215246" src="https://user-images.githubusercontent.com/39337503/151663638-9bea990b-f4b5-4326-9c45-1f3a05d8de64.png">
The latest commit "Fix transparency memes" didn't fix it.

**Comment by Kermalis** [comment]
It's very weird. I don't know what's so special about only those tiles, or what they have in common. The same types of artifacts are consistent along the bottom of the house, but not for the shadow over the path. Also not the top windows of the house. But then the mailbox is also messed up, and so is the archway to the cave. It's just hard to figure out

**Comment by Kermalis** [comment]
Try this branch: https://github.com/Kermalis/PokemonGameEngine/tree/testing-74
In the overworld, after it is finished fading in, you can press "L" on your controller or "Q" on your keyboard and it'll save all of the blocks to .png files in the program's folder. So check `PokemonGameEngine/bin/debug/net 6.0/Test`
You can look at it yourself but I'd prefer you send over a zip of that test folder so I can compare it to mine. If the glitches are present there then the problem lies in creating the block visuals rather than rendering them to the screen

**Comment by slango0513** [comment]
[Test.zip](https://github.com/Kermalis/PokemonGameEngine/files/7965382/Test.zip)

**Comment by Kermalis** [comment]
Ok yeah, it is a problem when creating the blocks initially, rather than a problem with the map renderer itself. Those images have the artifacts in them. I'll see what's up if I can

**Comment by Kermalis** [comment]
You can try the latest commit on that branch. It's less efficient but it may fix the problem

**Comment by slango0513** [comment]
<img width="1920" alt="屏幕截图 2022-01-30 182937" src="https://user-images.githubusercontent.com/39337503/151696039-b68c560b-1c36-41ec-9cf6-bc1630bf60e8.png">
<img width="1920" alt="屏幕截图 2022-01-30 182959" src="https://user-images.githubusercontent.com/39337503/151696047-f019e628-286d-417a-8357-73491d262d8e.png">
Gooood job ;)

**Comment by Kermalis** [comment]
Dang that's some weird stuff. Oh well, I'll look at how to optimize this solution, then commit it to the main branch :)

**Comment by Kermalis** [comment]
I know I closed this but can you check to see if the latest commit still works for you? I'll merge it if you confirm it still works

**Comment by slango0513** [comment]
Yes, it works (commit "Finish #74")
